name: palm_kissed_paws_driver
description: Palm Kissed Paws Transport - Driver App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Image handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Validation
  form_validator: ^1.0.0
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  
  # Real-time features
  socket_io_client: ^2.0.3+1
  
  # Push notifications
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.3.0
  
  # Utils
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/driver_app_icon.png"
  min_sdk_android: 21