name: palm_kissed_paws
description: Palm Kissed Paws Transport - Pet Transportation Service
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # HTTP & API
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Date & Time
  intl: ^0.18.1
  
  # Image handling
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  
  # Validation
  form_validator: ^1.0.0
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Payment
  flutter_stripe: ^9.5.0
  
  # Utils
  flutter_launcher_icons: ^0.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21